[package]
name = "os1"
version = "0.0.1"
edition = "2021"
license = "MIT"

[lints.clippy]
macro_metavars_in_unsafe = "allow"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "os1"
test = false
bench = false

[dependencies]
