[package]
name = "os1"
version = "0.0.1"
edition = "2021"
license = "MIT"

[lints.clippy]
new_without_default = "allow"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

# [[bin]]
# name = "os1"
# test = false

[dependencies]