[package]
name = "os1"
version = "0.0.1"
edition = "2021"
license = "MIT"

[workspace]
members = ["src/kernel"]

[build-dependencies]
bootloader = "0.11.10"
kernel = { path = "src/kernel", artifact = "bin", target = "x86_64-unknown-none" }

[dependencies]
ovmf-prebuilt = "0.1.0-alpha.1"
